package com.mrjuoss.dicoding.liverpoolplayer;

import java.util.ArrayList;

public class PlayerData {
    public static String[][] data = new String[][] {
            {"GOALKEEPERS", "Alisson Becker", "13", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69945_misc_general_500.jpeg", "Alisson arrived to the club in July 2018 from AS Roma and would enjoy an outstanding first season on Merseyside. Having penned a long-term deal, the goalkeeper was an immediate starter for Jürgen Klopp's side, wearing the No.13 shirt. He began his Liverpool career with a clean sheet in a 4-0 win over West Ham United at Anfield in the 2018-19 Premier League opener. He played every minute of the Reds' domestic campaign and made history when he became the club's first goalkeeper to win the Premier League Golden Glove award in over a decade after recording 21 clean sheets. The Brazil international was crucial in helping Liverpool win the Champions League for the sixth time. The shot-stopper preserved the Reds' spot in the knockout stages of the 2018-19 competition with a crucial late save against Napoli in matchday six win back in December 2018. He was then impenetrable in the Madrid final, making a series of interventions to deny Tottenham Hotspur as Klopp's men won 2-0. It was announced in April 2019 that Alisson would switch from No.13 to No.1 at the start of the 2019-20 campaign."},
            {"GOALKEEPERS", "Simon Mignolet", "22", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69999_misc_general_500.jpeg", "Mignolet made the move to Anfield in the summer of 2013 from Sunderland. Known to be the ultimate professional, the goalkeeper has clocked up over 200 appearances for the club. He began his Liverpool career in the best way possible when, on debut, he saved a late Stoke City penalty to preserve a 1-0 home win in the opening fixture of the 2013-14 Premier League season. After briefly being left out of the side in December 2014, the Belgian regained his place as first-choice stopper with a string of impressive performances in the remainder of the 2014-15 campaign. Mignolet maintained his place between the sticks following the arrival of Jürgen Klopp as manager and committed his future to the club by signing a long-term contract extension in January 2016. He saved two penalties in a shootout against Stoke to secure Liverpool's place in the 2015-16 League Cup final. A tussle for the No.1 jersey then ensued following the arrival of Loris Karius for the next two seasons until Alisson Becker was signed in July 2018. After Karius joined Besiktas on a two-year loan, Mignolet spent the 2018-19 as deputy to Alisson, but was lauded for his professionalism by teammates and the club's coaching staff.."},
            {"GOALKEEPERS", "Caoimhin Kelleher", "62", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69996_misc_general_500.jpeg", "Liverpool secured the services of the talented Irish goalkeeper in the summer of 2015. Caomhin, pronounced Quivine, was born in Cork and joined the Reds from Ringmahon Rangers. Having progressed through the ranks at the club's Academy, Kelleher trains with the first team at Melwood. He made three friendly appearances for the senior side in pre-season ahead of the 2018-19 campaign and was on the bench for the FA Cup third-round tie at Wolverhampton Wanderers. The shot-stopper collected a winner's medal after Liverpool beat Tottenham Hotspur in the 2019 Champions League final. Kelleher received his first senior call-up to the Republic of Ireland national team in November 2018."},
            {"DEFENDERS", "Virgil van Dijk", "04", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70012_misc_general_500.jpeg", "Virgil van Dijk has established himself as one of the finest defenders in world football since joining Liverpool in January 2018. The powerful Netherlands international, who combines a graceful reading of the game with a dominant physical skillset, helped the Reds clinch a sixth European Cup at the conclusion of his first full season with the club. Victory over Tottenham Hotspur in Madrid secured a first piece of silverware at Liverpool for Van Dijk, who missed just 35 minutes of Premier League action in 2018-19 as Jürgen Klopp’s side finished second with a club-record 97 points. He was an outstanding presence at the heart of the defence as the Reds eliminated Bayern Munich – against whom he scored in a crucial second-leg win in Germany – as well as FC Porto and FC Barcelona on the road to a second successive Champions League final. And there was redemption in the showpiece as Van Dijk and co bounced back from their defeat by Real Madrid a year earlier to see off Spurs 2-0 and lift the trophy at Estadio Metropolitano. Such was the No.4’s imperious form throughout the campaign, he was voted PFA Players’ Player of the Year by his peers and also collected the Premier League Player of the Season award."},
            {"DEFENDERS", "Dejan Lovren", "06", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/72/thumb_71690_misc_general_500.jpeg", "Liverpool continued their recruitment drive for the 2014-15 season by landing powerful centre-back Dejan Lovren from Southampton. The Croatian international boasts a gleaming CV, which includes Champions League and World Cup experience. Strong, dominant in the air and offering a composed presence, Lovren also boasts great leadership qualities, which helped him make a rapid rise to playing top-level football. Born in the town of Zenica, on July 5 1989, Lovren began his youth career at NK Karlovac. By 2004 he had alerted the attention of Dinamo Zagreb after impressing their academy coach whilst playing against them. Indeed, such was his rise to prominence, he was even included in their senior squad shortly before his 17th birthday. At the start of the 2007-08 season - his first full professional campaign - Lovren was loaned out to newly promoted NK Inter Zapresic, where he gained vital top-flight experience by starting 29 out of a possible 33 league games as the team finished in 11th position."},
            {"DEFENDERS", "Joe Gomez", "12", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69956_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"DEFENDERS", "Andy Robertson", "26", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70006_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"DEFENDERS", "Joel Matip", "32", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69998_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"DEFENDERS", "Trent Alexander-Arnold", "66", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70011_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Fabinho", "03", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69953_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Georginio Wijnaldum", "05", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70013_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "James Milner", "07", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/72/thumb_71691_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Naby Keita", "08", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69990_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Jordan Henderson", "14", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69958_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Alex Oxlade-Chamberlain", "21", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/72/thumb_71693_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"MIDFIELDERS", "Xerdhan Xhaqiri", "23", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70009_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"FORWARDS", "Roberto Firmino", "09", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69955_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"FORWARDS", "Sadio Mane", "10", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/70/thumb_69997_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
            {"FORWARDS", "Mohamed Salah", "11", "https://d3j2s6hdd6a7rg.cloudfront.net/v2/uploads/media/misc/0001/71/thumb_70007_misc_general_500.jpeg", "Liverpool continued their recruitment drive e to prominence. "},
    };

    public static ArrayList<Player> getListData() {
        Player player = null;
        ArrayList<Player> list = new ArrayList<>();
        for (String[] aData : data) {
            player = new Player();
            player.setGroup(aData[0]);
            player.setName(aData[1]);
            player.setNumber(aData[2]);
            player.setPhoto(aData[3]);
            player.setDescription(aData[4]);

            list.add(player);
        }

        return list;
    }
}
